import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import java.util.concurrent.TimeUnit;

public class WebDriverEx {
    public static void main(String[] args) throws InterruptedException {
        WebDriver driver = new ChromeDriver();
        Actions hover = new Actions(driver);
        driver.get("https://passport.yandex.ru/auth?origin=home_desktop_ru&retpath=https%3A%2F%2Fmail.yandex.ru%2F&backpath=https%3A%2F%2Fyandex.ru");
        Auth(driver);
        Test1_SendEmailWithSubject(driver, hover);
        Test2_DeleteEmail(driver, hover);
        Test3_EmailMoveToFolder(driver, hover);
        Test4_EmailSearch(driver, hover);
        Test5_EmailMark(driver, hover);
    }

    public static void Auth(WebDriver driver) throws InterruptedException {
        WebElement loginField = driver.findElement(By.id("passp-field-login"));
        loginField.click();
        loginField.sendKeys("kingofjedi");
        loginField.submit();
        WebDriverWait wait = new WebDriverWait(driver, 10);
        wait.until(ExpectedConditions.elementToBeClickable(By.id("passp-field-passwd")));
        WebElement passwordField = driver.findElement(By.id("passp-field-passwd"));
        passwordField.click();
        passwordField.sendKeys("mamavaio");
        passwordField.submit();
        Thread.sleep(   10000);
    }

    public static void Test1_SendEmailWithSubject(WebDriver driver, Actions hover) throws InterruptedException {
        System.out.println("Test 1 started");
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
        WebElement composeButton = driver.findElement(By.className("mail-ComposeButton-Text"));
        composeButton.click();
        WebElement emailField = driver.findElement(By.className("composeYabbles"));
        emailField.sendKeys("kingofjedi@yandex.ru");
        WebElement subjectField = driver.findElement(By.name("subject"));
        subjectField.sendKeys("This email generated by Selenium AT");
        WebElement sendButton = driver.findElement(By.xpath("//body/div[2]/div[10]/div/div[2]/div/div[2]/div/div[1]/div[2]/div[2]/div/div[1]/div[1]/button"));
        hover.moveToElement(sendButton).perform();
        sendButton.click();
        System.out.println("Test 1 completed");
        Thread.sleep(5000);
        driver.navigate().refresh();
        Thread.sleep(5000);
    }

    public static void Test2_DeleteEmail(WebDriver driver, Actions hover) {
        System.out.println("Test 2 started");
        hover.moveToElement(driver.findElement(By.xpath("//body/div[2]/div[6]/div/div[3]/div[3]/div[2]/div[5]/div[1]/div/div/div[2]/div/div[1]/div/div/div/a/div/span[1]/div/div/div[2]/label"))).perform();
        driver.findElement(By.xpath("//body/div[2]/div[6]/div/div[3]/div[3]/div[2]/div[5]/div[1]/div/div/div[2]/div/div[1]/div/div/div/a/div/span[1]/div/div/div[2]/label")).click();
        hover.moveToElement(driver.findElement(By.xpath("//body/div[2]/div[6]/div/div[3]/div[3]/div[2]/div[2]/div[2]/div/div[2]/div/div/div[5]"))).perform();
        driver.findElement(By.xpath("//body/div[2]/div[6]/div/div[3]/div[3]/div[2]/div[2]/div[2]/div/div[2]/div/div/div[5]")).click();
        System.out.println("Test 2 completed");
    }

    public static void Test3_EmailMoveToFolder(WebDriver driver, Actions hover)  {
        System.out.println("Test 3 started");
        hover.moveToElement(driver.findElement(By.xpath("//body/div[2]/div[6]/div/div[3]/div[3]/div[2]/div[5]/div[1]/div/div/div[2]/div/div[1]/div/div/div/a/div/span[1]/div/div/div[2]/label"))).perform();
        driver.findElement(By.xpath("//body/div[2]/div[6]/div/div[3]/div[3]/div[2]/div[5]/div[1]/div/div/div[2]/div/div[1]/div/div/div/a/div/span[1]/div/div/div[2]/label")).click();
        hover.moveToElement(driver.findElement(By.xpath("//body/div[2]/div[6]/div/div[3]/div[3]/div[2]/div[2]/div[2]/div/div[2]/div/div/div[12]"))).perform();
        driver.findElement(By.xpath("//body/div[2]/div[6]/div/div[3]/div[3]/div[2]/div[2]/div[2]/div/div[2]/div/div/div[12]")).click();
        driver.findElement(By.xpath("//div/div/div[2]/div[1]/div[5]/span/a")).click();
        System.out.println("Test 3 completed");
    }

    public static void Test4_EmailSearch(WebDriver driver, Actions hover) throws InterruptedException {
        System.out.println("Test 4 started");
        WebElement searchField = driver.findElement(By.xpath("//body/div[2]/div[6]/div/div[2]/div/div/header/div/div[3]/div/div/div/div[1]/form/div/span/input"));
        hover.moveToElement(searchField).perform();
        searchField.click();
        Thread.sleep(4000);
        searchField.sendKeys("Mail for search");
        Thread.sleep(4000);
        WebElement searchButton = driver.findElement(By.xpath("//body/div[2]/div[6]/div/div[2]/div/div/header/div/div[3]/div/div/div/div[1]/form/button"));
        hover.moveToElement(searchButton).perform();
        searchButton.click();
        Thread.sleep(4000);
        WebElement searchedEmail = driver.findElement(By.xpath("//body/div[2]/div[6]/div/div[3]/div[3]/div[2]/div[5]/div[1]/div/div/div[2]/div/div[3]/div/div/div/a/div/span[2]"));
        hover.moveToElement(searchedEmail).perform();
        searchedEmail.click();
        System.out.println("Test 4 completed");
        Thread.sleep(4000);
    }

    public static void Test5_EmailMark(WebDriver driver, Actions hover) throws InterruptedException {
        System.out.println("Test 5 started");
        WebElement mailingLists = driver.findElement(By.xpath("//body/div[2]/div[6]/div/div[3]/div[2]/div[3]/div/div[1]/div[1]/a[2]"));
        hover.moveToElement(mailingLists).perform();
        mailingLists.click();
        Thread.sleep(4000);
        WebElement marker = driver.findElement(By.xpath("//body/div[2]/div[6]/div/div[3]/div[3]/div[2]/div[5]/div[1]/div/div/div[2]/div/div[1]/div/div/div/a/div/span[1]/span[1]"));
        hover.moveToElement(marker).perform();
        marker.click();
        System.out.println("Test 5 completed");
    }
}
